name: gestion_reclamations_citoyens
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_animations: any
  webview_flutter: any
  http: any
  fluttertoast: any
  font_awesome_flutter: any
  flutter_facebook_login: any
  google_sign_in: any
  shared_preferences: any
  image_picker: any
  flutter_map: any
  animated_splash_screen: any
  flutter_map_arcgis: any
  dio: any
  latlng: any
  flutter_svg: any
  mailto: any
  url_launcher: any
  odoo_api: any
  settings_ui: any
  rflutter_alert: any
  geocoding: any
  geolocator: any
  slimy_card: any
  flutter_mobile_vision: any
  easy_localization: any
  local_auth: any
  multi_image_picker: any
  flutter_absolute_path: any
  html: any
  flutter_local_notifications: any
  timezone: any
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: any
  
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/onboarding1.png
    - assets/Phone.jpg
    - assets/claim.jpg
    - assets/protest.png
    - assets/mobile.png
    - assets/map.png
    - assets/l.png
    - assets/login.svg
    - assets/signup.svg
    - assets/complain.png
    - assets/image.jpg
    - assets/data/data.json
    - assets/loop.gif
    - assets/signup.gif
    - assets/login.gif
    - assets/paper.gif
    - assets/wave.svg
    - assets/wave2.svg
    - assets/wave3.svg
    - assets/blue.jpg
    - assets/main_top.png
    - assets/main_bottom.png
    - assets/signup_top.png
    - assets/login_bottom.png
    - assets/data/code.json
    - assets/undraw_pilates_gpdb.png
    - assets/menu.svg
    - assets/person.jpg
    - assets/technician.jpg
    - assets/tech.png
    - assets/per.png
    - assets/add.gif
    - assets/update.gif
    - assets/locales/
    - assets/commune.svg
    - assets/signal.jpg
    - assets/fuite.jpg
    - assets/eclairage.jpg
    - assets/place.jpg
    - assets/téléchargement.png
    - assets/autres.png
    - assets/Propreté-déchets.jpg
    - assets/images.jpg
    - assets/icons/
    - assets/images/
    - assets/imgpsh_fullsize_anim.png
    - assets/news.png
    - assets/run_results.json

       
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
